name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set CI environment variable to false
      run: echo "CI=false" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name "Waelahmed99"
        git config --global user.email "waelahmed6599@gmail.com"


    - name: Install dependencies
      run: npm install

    - name: Install gh-pages
      run: npm install gh-pages --save-dev

    - name: Build and deploy to GitHub Pages
      run: |
        npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
