name: CI/CD

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Install dependencies
      run: npm install
    
    - name: Lint code
      run: npm run lint
    
    - name: Test code
      run: npm test
    
    - name: Build code
      run: npm run build
